experiment:
    id: fasterrcnn
    seed: 1324

checkpoint: './output/frcnn_beets/'
tensorboard: './output/frcnn_beets/'

##Data
data:
    # train: '/mnt/d/datasets/UoS_Drone/beets/'
    # val: '/mnt/d/datasets/UoS_Drone/beets/'
    # train: '/mnt/d/datasets/Phenobench/train/'
    # val: '/mnt/d/datasets/Phenobench/val/'

images:
    # dir: '/mnt/d/datasets/UoS_Drone/beets/images/'
    dir: '/mnt/d/datasets/portal_rawdatasets/canola_uav/'
    tile: 1024

##Training
train:
    n_gpus: 1
    workers: 0
    max_epoch: 200
    batch_size: 1
    n_classes: 3
    overfit: False
    lr: 0.0001

val:
    nms_th: 0.5
    prob_th: 0.6
